spring:
  application:
    name: base_spring_boot
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/base_core?createDatabaseIfNotExist=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Phuchb24@}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    key: ${JWT_SECRET:daylachuoimahoabimatrikkei0987654321dacbietracroi}
  expired:
    access: 864000
    refresh: 604800000

cloudinary:
  cloud-name: acsu345
  api-key: 973697993839398
  api-secret: Qd9mnuWKGiQ4p0fd8YPVVd4B2jQ

