spring:
  application:
    name: base_spring_boot
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/base_core?createDatabaseIfNotExist=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:Phuchb24@}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret:
    key: ${JWT_SECRET:daylachuoimahoabimatrikkei0987654321dacbietracroi}
  expired:
    access: 864000
    refresh: 604800000